objects-y+=main.o led.o 
objects-$(USE_MOVEMENT)+=movement.o
objects-$(USE_PID)+=pid.o
objects-$(USE_COORDS)+=deltacords.o
objects-$(USE_CHASSIS)+=chassis.o
objects-$(USE_ENCODERS)+=encoder.o
objects-$(USE_UART)+=uart.o
