objects-y+=main.o led.o 
objects-$(CONFIG_USE_MOVEMENT)+=movement.o
objects-$(CONFIG_USE_PID)+=pid.o
objects-$(CONFIG_USE_COORDS)+=deltacoords.o
objects-$(CONFIG_USE_CHASSIS)+=chassis.o
objects-$(CONFIG_USE_ENCODERS)+=encoders.o
objects-$(CONFIG_USE_UART)+=uart.o
objects-$(CONFIG_USE_SENSORS)+=sensors.o

subdirs-$(CONFIG_USE_PERIPHBOARD)+=periph
